{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1706ece4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-----------------------------------------\n",
      "keras-unet init: TF version is >= 2.0.0 - using `tf.keras` instead of `Keras`\n",
      "-----------------------------------------\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "import tensorflow.keras as keras\n",
    "\n",
    "import DLlib as dl\n",
    "import pylib as py\n",
    "import tf2lib as tl\n",
    "import tf2gan as gan\n",
    "import wflib as wf\n",
    "\n",
    "import data\n",
    "from keras_unet.models import custom_unet\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as patches\n",
    "import tqdm\n",
    "import h5py\n",
    "import xlsxwriter\n",
    "from skimage.metrics import structural_similarity\n",
    "from itertools import cycle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b05fad39",
   "metadata": {},
   "outputs": [],
   "source": [
    "experiment_dir = 'output/Unsup-005'\n",
    "out_vars = 'PM'\n",
    "n_echoes = 6\n",
    "G_model = 'encod-decod'\n",
    "te_input = True\n",
    "bayesian = True\n",
    "n_filters = 64\n",
    "batch_size = 1\n",
    "D1_SelfAttention = False\n",
    "D2_SelfAttention = True\n",
    "D3_SelfAttention = False"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "02fef358",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Num. Elements- DS1: 1\n"
     ]
    }
   ],
   "source": [
    "############################################################\n",
    "############### DIRECTORIES AND FILENAMES ##################\n",
    "############################################################\n",
    "dataset_dir = '../MATLAB/waterFatSignalPhantom/data_out/'\n",
    "dataset_hdf5_1 = 'phantom.hdf5'\n",
    "\n",
    "############################################################\n",
    "################### LOAD DATASET 1 #########################\n",
    "############################################################\n",
    "if G_model == 'complex':\n",
    "    ech_idx = n_echoes\n",
    "else:\n",
    "    ech_idx = n_echoes * 2\n",
    "acqs_1, out_maps_1 = data.load_hdf5(dataset_dir,dataset_hdf5_1, ech_idx, complex_data=(G_model=='complex'))\n",
    "\n",
    "print('Num. Elements- DS1:', len(acqs_1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9ffd7b9f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Acquisition Dimensions: 192 192\n",
      "Echoes: 6\n",
      "Output Maps: 6\n",
      "Testing input shape: (1, 192, 192, 12)\n",
      "Testing output shape: (1, 192, 192, 6)\n"
     ]
    }
   ],
   "source": [
    "############################################################\n",
    "################# DATASET PARTITIONS #######################\n",
    "############################################################\n",
    "\n",
    "testX   = acqs_1\n",
    "\n",
    "testY   = out_maps_1\n",
    "\n",
    "# Overall dataset statistics\n",
    "len_dataset,hgt,wdt,d_ech = np.shape(testX)\n",
    "_,_,_,n_out = np.shape(testY)\n",
    "echoes = int(d_ech/2)\n",
    "r2_sc,fm_sc = 200,300\n",
    "\n",
    "print('Acquisition Dimensions:', hgt,wdt)\n",
    "print('Echoes:',echoes)\n",
    "print('Output Maps:',n_out)\n",
    "\n",
    "# Input and output dimensions (testing data)\n",
    "print('Testing input shape:',testX.shape)\n",
    "print('Testing output shape:',testY.shape)\n",
    "\n",
    "A_B_dataset_test = tf.data.Dataset.from_tensor_slices((testX,testY))\n",
    "A_B_dataset_test.batch(batch_size)\n",
    "test_iter = cycle(A_B_dataset_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "86041f5f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x000002CF907EA310> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908333D0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF907A0EE0> and <tensorflow.python.keras.layers.core.Dense object at 0x000002CF907EA310>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF907EC730> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90833F40>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF908102E0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907A0E20>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF907A01C0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907A0C40>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x000002CF908156D0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90833E80>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF90845F10> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907A0B50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF9089BEB0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90833220>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF9089B940> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90865AC0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF9082F8B0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907A04F0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x000002CF908DEC10> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908658B0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF908C0EB0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907ECE20>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF9092C5E0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907F53A0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF9092C3A0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907F5F10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF90922EE0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90842880>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x000002CF90941BB0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907A07F0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF9094A8B0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF907D6850>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF909792E0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x000002CF90807A30>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF90980040> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF908102E0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF90994490> and <tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF907A01C0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CF909A0F70> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908641C0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CF909947F0> and <tensorflow.python.keras.layers.core.Dense object at 0x000002CF908156D0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<DLlib.attention.SelfAttention object at 0x000002CF909802B0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90864040>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF909B7DC0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C0E50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0F042E0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90864EE0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF909C6FA0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C02E0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA1002400> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908646D0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF909CF9D0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C0610>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0FB4E20> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9082FA90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0EFDD00> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C0940>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0FBC160> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C0370>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CFE3C3C1C0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9082FC10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CFA0FF54F0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C0EE0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0FCD400> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C0AC0>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0FDB640> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9082F130>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF907E0AC0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9082F0D0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0F54820> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9082F730>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF907EA520> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9082F4C0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA102A6A0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x000002CF9081D9D0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0F7C3A0> and <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CF9089B940>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0FC2EE0> and <tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CF9082F8B0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CFA1030610> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9091E7F0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CFA0FC17F0> and <tensorflow.python.keras.layers.core.Dense object at 0x000002CF908DEC10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0FE43A0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9091EB20>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0F4EC10> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90922190>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0F37BE0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9091E430>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0F5FF40> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90922940>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0F46670> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9091E6A0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0F67640> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90922880>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0F46D60> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9091E100>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA1033E50> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90922070>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CFA105E910> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90918D00>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2DTranspose object at 0x000002CFA1057670> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9091E2B0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0F90220> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90918CD0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0F88880> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90918880>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA0F9EA60> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90918D30>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.normalizations.InstanceNormalization object at 0x000002CFA1070C10> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF90918BE0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA0F9ED60> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF9091E850>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x000002CFA107B2B0> and <tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer object at 0x000002CF908C0CA0>).\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Shapes (3, 3, 128, 256) and (3, 3, 256, 256) are incompatible",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Input \u001b[1;32mIn [5]\u001b[0m, in \u001b[0;36m<cell line: 47>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m(\u001b[38;5;167;01mNameError\u001b[39;00m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mUnrecognized Generator Architecture\u001b[39m\u001b[38;5;124m'\u001b[39m))\n\u001b[0;32m     46\u001b[0m \u001b[38;5;66;03m# restore\u001b[39;00m\n\u001b[1;32m---> 47\u001b[0m \u001b[43mtl\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mCheckpoint\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mdict\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mG_A2B\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mG_A2B\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpy\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mjoin\u001b[49m\u001b[43m(\u001b[49m\u001b[43mexperiment_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mcheckpoints\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\Documents\\OT-CycleGAN\\tf2lib\\utils\\utils.py:17\u001b[0m, in \u001b[0;36mCheckpoint.restore\u001b[1;34m(self, save_path)\u001b[0m\n\u001b[0;32m     15\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrestore\u001b[39m(\u001b[38;5;28mself\u001b[39m, save_path\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[0;32m     16\u001b[0m     save_path \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmanager\u001b[38;5;241m.\u001b[39mlatest_checkpoint \u001b[38;5;28;01mif\u001b[39;00m save_path \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;28;01melse\u001b[39;00m save_path\n\u001b[1;32m---> 17\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcheckpoint\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43msave_path\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\tracking\\util.py:2118\u001b[0m, in \u001b[0;36mCheckpoint.restore\u001b[1;34m(self, save_path, options)\u001b[0m\n\u001b[0;32m   2037\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrestore\u001b[39m(\u001b[38;5;28mself\u001b[39m, save_path, options\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[0;32m   2038\u001b[0m   \u001b[38;5;124;03m\"\"\"Restore a training checkpoint.\u001b[39;00m\n\u001b[0;32m   2039\u001b[0m \n\u001b[0;32m   2040\u001b[0m \u001b[38;5;124;03m  Restores this `Checkpoint` and any objects it depends on.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   2116\u001b[0m \u001b[38;5;124;03m        (often at program shutdown).\u001b[39;00m\n\u001b[0;32m   2117\u001b[0m \u001b[38;5;124;03m  \"\"\"\u001b[39;00m\n\u001b[1;32m-> 2118\u001b[0m   status \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mread\u001b[49m\u001b[43m(\u001b[49m\u001b[43msave_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moptions\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   2119\u001b[0m   \u001b[38;5;66;03m# Create the save counter now so it gets initialized with other variables\u001b[39;00m\n\u001b[0;32m   2120\u001b[0m   \u001b[38;5;66;03m# when graph building. Creating it earlier would lead to errors when using,\u001b[39;00m\n\u001b[0;32m   2121\u001b[0m   \u001b[38;5;66;03m# say, train.Saver() to save the model before initializing it.\u001b[39;00m\n\u001b[0;32m   2122\u001b[0m   \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_maybe_create_save_counter()\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\tracking\\util.py:2035\u001b[0m, in \u001b[0;36mCheckpoint.read\u001b[1;34m(self, save_path, options)\u001b[0m\n\u001b[0;32m   1997\u001b[0m \u001b[38;5;124;03m\"\"\"Read a training checkpoint written with `write`.\u001b[39;00m\n\u001b[0;32m   1998\u001b[0m \n\u001b[0;32m   1999\u001b[0m \u001b[38;5;124;03mReads this `Checkpoint` and any objects it depends on.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   2032\u001b[0m \u001b[38;5;124;03m  status of a checkpoint restoration.  See `restore` for details.\u001b[39;00m\n\u001b[0;32m   2033\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m   2034\u001b[0m options \u001b[38;5;241m=\u001b[39m options \u001b[38;5;129;01mor\u001b[39;00m checkpoint_options\u001b[38;5;241m.\u001b[39mCheckpointOptions()\n\u001b[1;32m-> 2035\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_saver\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43msave_path\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msave_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moptions\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\tracking\\util.py:1319\u001b[0m, in \u001b[0;36mTrackableSaver.restore\u001b[1;34m(self, save_path, options)\u001b[0m\n\u001b[0;32m   1311\u001b[0m object_graph_proto\u001b[38;5;241m.\u001b[39mParseFromString(object_graph_string)\n\u001b[0;32m   1312\u001b[0m checkpoint \u001b[38;5;241m=\u001b[39m _CheckpointRestoreCoordinator(\n\u001b[0;32m   1313\u001b[0m     object_graph_proto\u001b[38;5;241m=\u001b[39mobject_graph_proto,\n\u001b[0;32m   1314\u001b[0m     save_path\u001b[38;5;241m=\u001b[39msave_path,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1317\u001b[0m     graph_view\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_graph_view,\n\u001b[0;32m   1318\u001b[0m     options\u001b[38;5;241m=\u001b[39moptions)\n\u001b[1;32m-> 1319\u001b[0m \u001b[43mbase\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mCheckpointPosition\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   1320\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcheckpoint\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcheckpoint\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mproto_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_graph_view\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mroot\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1321\u001b[0m load_status \u001b[38;5;241m=\u001b[39m CheckpointLoadStatus(\n\u001b[0;32m   1322\u001b[0m     checkpoint,\n\u001b[0;32m   1323\u001b[0m     graph_view\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_graph_view,\n\u001b[0;32m   1324\u001b[0m     feed_dict\u001b[38;5;241m=\u001b[39mfile_prefix_feed_dict)\n\u001b[0;32m   1325\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m load_status\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\tracking\\base.py:209\u001b[0m, in \u001b[0;36mCheckpointPosition.restore\u001b[1;34m(self, trackable)\u001b[0m\n\u001b[0;32m    205\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m ops\u001b[38;5;241m.\u001b[39minit_scope():\n\u001b[0;32m    206\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbind_object(trackable):\n\u001b[0;32m    207\u001b[0m     \u001b[38;5;66;03m# This object's correspondence with a checkpointed object is new, so\u001b[39;00m\n\u001b[0;32m    208\u001b[0m     \u001b[38;5;66;03m# process deferred restorations for it and its dependencies.\u001b[39;00m\n\u001b[1;32m--> 209\u001b[0m     restore_ops \u001b[38;5;241m=\u001b[39m \u001b[43mtrackable\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_restore_from_checkpoint_position\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m)\u001b[49m  \u001b[38;5;66;03m# pylint: disable=protected-access\u001b[39;00m\n\u001b[0;32m    210\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m restore_ops:\n\u001b[0;32m    211\u001b[0m       \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_checkpoint\u001b[38;5;241m.\u001b[39mnew_restore_ops(restore_ops)\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\tracking\\base.py:913\u001b[0m, in \u001b[0;36mTrackable._restore_from_checkpoint_position\u001b[1;34m(self, checkpoint_position)\u001b[0m\n\u001b[0;32m    910\u001b[0m   tensor_saveables\u001b[38;5;241m.\u001b[39mupdate(new_tensor_saveables)\n\u001b[0;32m    911\u001b[0m   python_saveables\u001b[38;5;241m.\u001b[39mextend(new_python_saveables)\n\u001b[0;32m    912\u001b[0m restore_ops\u001b[38;5;241m.\u001b[39mextend(\n\u001b[1;32m--> 913\u001b[0m     \u001b[43mcurrent_position\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcheckpoint\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore_saveables\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    914\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtensor_saveables\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpython_saveables\u001b[49m\u001b[43m)\u001b[49m)\n\u001b[0;32m    915\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m restore_ops\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\tracking\\util.py:296\u001b[0m, in \u001b[0;36m_CheckpointRestoreCoordinator.restore_saveables\u001b[1;34m(self, tensor_saveables, python_saveables)\u001b[0m\n\u001b[0;32m    292\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mset\u001b[39m(tensor_saveables\u001b[38;5;241m.\u001b[39mkeys()) \u001b[38;5;241m!=\u001b[39m validated_names:\n\u001b[0;32m    293\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAssertionError\u001b[39;00m(\n\u001b[0;32m    294\u001b[0m       (\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mSaveable keys changed when validating. Got back \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m, was \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    295\u001b[0m        \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mexpecting \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;241m%\u001b[39m (tensor_saveables\u001b[38;5;241m.\u001b[39mkeys(), validated_names))\n\u001b[1;32m--> 296\u001b[0m new_restore_ops \u001b[38;5;241m=\u001b[39m \u001b[43mfunctional_saver\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mMultiDeviceSaver\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    297\u001b[0m \u001b[43m    \u001b[49m\u001b[43mvalidated_saveables\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msave_path_tensor\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    298\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m context\u001b[38;5;241m.\u001b[39mexecuting_eagerly():\n\u001b[0;32m    299\u001b[0m   \u001b[38;5;28;01mfor\u001b[39;00m name, restore_op \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28msorted\u001b[39m(new_restore_ops\u001b[38;5;241m.\u001b[39mitems()):\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\saving\\functional_saver.py:340\u001b[0m, in \u001b[0;36mMultiDeviceSaver.restore\u001b[1;34m(self, file_prefix, options)\u001b[0m\n\u001b[0;32m    338\u001b[0m   restore_ops \u001b[38;5;241m=\u001b[39m tf_function_restore()\n\u001b[0;32m    339\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m--> 340\u001b[0m   restore_ops \u001b[38;5;241m=\u001b[39m \u001b[43mrestore_fn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    342\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m callback \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_after_restore_callbacks:\n\u001b[0;32m    343\u001b[0m   callback()\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\saving\\functional_saver.py:316\u001b[0m, in \u001b[0;36mMultiDeviceSaver.restore.<locals>.restore_fn\u001b[1;34m()\u001b[0m\n\u001b[0;32m    314\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m device, saver \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28msorted\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_single_device_savers\u001b[38;5;241m.\u001b[39mitems()):\n\u001b[0;32m    315\u001b[0m   \u001b[38;5;28;01mwith\u001b[39;00m ops\u001b[38;5;241m.\u001b[39mdevice(device):\n\u001b[1;32m--> 316\u001b[0m     restore_ops\u001b[38;5;241m.\u001b[39mupdate(\u001b[43msaver\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile_prefix\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moptions\u001b[49m\u001b[43m)\u001b[49m)\n\u001b[0;32m    318\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m restore_ops\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\saving\\functional_saver.py:110\u001b[0m, in \u001b[0;36m_SingleDeviceSaver.restore\u001b[1;34m(self, file_prefix, options)\u001b[0m\n\u001b[0;32m    107\u001b[0m restore_ops \u001b[38;5;241m=\u001b[39m {}\n\u001b[0;32m    108\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m saveable, restored_tensors \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mzip\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_saveable_objects,\n\u001b[0;32m    109\u001b[0m                                       structured_restored_tensors):\n\u001b[1;32m--> 110\u001b[0m   restore_ops[saveable\u001b[38;5;241m.\u001b[39mname] \u001b[38;5;241m=\u001b[39m \u001b[43msaveable\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrestore\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    111\u001b[0m \u001b[43m      \u001b[49m\u001b[43mrestored_tensors\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrestored_shapes\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[0;32m    112\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m restore_ops\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\training\\saving\\saveable_object_util.py:126\u001b[0m, in \u001b[0;36mResourceVariableSaveable.restore\u001b[1;34m(self, restored_tensors, restored_shapes)\u001b[0m\n\u001b[0;32m    124\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m ops\u001b[38;5;241m.\u001b[39mdevice(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_var_device):\n\u001b[0;32m    125\u001b[0m   restored_tensor \u001b[38;5;241m=\u001b[39m array_ops\u001b[38;5;241m.\u001b[39midentity(restored_tensor)\n\u001b[1;32m--> 126\u001b[0m   \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mresource_variable_ops\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mshape_safe_assign_variable_handle\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    127\u001b[0m \u001b[43m      \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mhandle_op\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_var_shape\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrestored_tensor\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\ops\\resource_variable_ops.py:311\u001b[0m, in \u001b[0;36mshape_safe_assign_variable_handle\u001b[1;34m(handle, shape, value, name)\u001b[0m\n\u001b[0;32m    309\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m _handle_graph(handle):\n\u001b[0;32m    310\u001b[0m   value_tensor \u001b[38;5;241m=\u001b[39m ops\u001b[38;5;241m.\u001b[39mconvert_to_tensor(value)\n\u001b[1;32m--> 311\u001b[0m \u001b[43mshape\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43massert_is_compatible_with\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvalue_tensor\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mshape\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    312\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m gen_resource_variable_ops\u001b[38;5;241m.\u001b[39massign_variable_op(handle,\n\u001b[0;32m    313\u001b[0m                                                     value_tensor,\n\u001b[0;32m    314\u001b[0m                                                     name\u001b[38;5;241m=\u001b[39mname)\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1134\u001b[0m, in \u001b[0;36mTensorShape.assert_is_compatible_with\u001b[1;34m(self, other)\u001b[0m\n\u001b[0;32m   1122\u001b[0m \u001b[38;5;124;03m\"\"\"Raises exception if `self` and `other` do not represent the same shape.\u001b[39;00m\n\u001b[0;32m   1123\u001b[0m \n\u001b[0;32m   1124\u001b[0m \u001b[38;5;124;03mThis method can be used to assert that there exists a shape that both\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1131\u001b[0m \u001b[38;5;124;03m  ValueError: If `self` and `other` do not represent the same shape.\u001b[39;00m\n\u001b[0;32m   1132\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m   1133\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mis_compatible_with(other):\n\u001b[1;32m-> 1134\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mShapes \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m and \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m are incompatible\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m (\u001b[38;5;28mself\u001b[39m, other))\n",
      "\u001b[1;31mValueError\u001b[0m: Shapes (3, 3, 128, 256) and (3, 3, 256, 256) are incompatible"
     ]
    }
   ],
   "source": [
    "# model\n",
    "if G_model == 'multi-decod' or G_model == 'encod-decod':\n",
    "    if out_vars == 'WF-PM':\n",
    "        G_A2B=dl.MDWF_Generator(input_shape=(hgt,wdt,d_ech),\n",
    "                                te_input=te_input,\n",
    "                                filters=n_filters,\n",
    "                                WF_self_attention=D1_SelfAttention,\n",
    "                                R2_self_attention=D2_SelfAttention,\n",
    "                                FM_self_attention=D3_SelfAttention)\n",
    "    else:\n",
    "        G_A2B = dl.PM_Generator(input_shape=(hgt,wdt,d_ech),\n",
    "                                te_input=te_input,\n",
    "                                te_shape=(n_echoes,),\n",
    "                                bayesian=bayesian,\n",
    "                                filters=n_filters,\n",
    "                                R2_self_attention=D1_SelfAttention,\n",
    "                                FM_self_attention=D2_SelfAttention)\n",
    "\n",
    "elif G_model == 'U-Net':\n",
    "    if out_vars == 'WF-PM':\n",
    "        n_out = 4\n",
    "    else:\n",
    "        n_out = 2\n",
    "    G_A2B = custom_unet(input_shape=(hgt,wdt,d_ech),\n",
    "                        num_classes=n_out,\n",
    "                        dropout=0.0,\n",
    "                        use_dropout_on_upsampling=True,\n",
    "                        use_attention=D1_SelfAttention,\n",
    "                        filters=n_filters)\n",
    "\n",
    "elif G_model == 'MEBCRN':\n",
    "    if out_vars == 'WF-PM':\n",
    "        n_out = 4\n",
    "    else:\n",
    "        n_out = 2\n",
    "    G_A2B=dl.MEBCRN(input_shape=(hgt,wdt,d_ech),\n",
    "                    n_outputs=n_out,\n",
    "                    n_res_blocks=5,\n",
    "                    n_downsamplings=2,\n",
    "                    filters=n_filters,\n",
    "                    self_attention=D1_SelfAttention)\n",
    "\n",
    "else:\n",
    "    raise(NameError('Unrecognized Generator Architecture'))\n",
    "\n",
    "# restore\n",
    "tl.Checkpoint(dict(G_A2B=G_A2B), py.join(experiment_dir, 'checkpoints')).restore()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f64618c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Reduced-Ideal model\n",
    "@tf.function\n",
    "def sample_A2B(A,TE=None):\n",
    "    indx_B = tf.concat([tf.zeros_like(A[:,:,:,:4],dtype=tf.int32),\n",
    "                        tf.ones_like(A[:,:,:,:2],dtype=tf.int32)],axis=-1)\n",
    "    indx_B_abs = tf.concat([tf.zeros_like(A[:,:,:,:2],dtype=tf.int32),\n",
    "                            tf.ones_like(A[:,:,:,:2],dtype=tf.int32)],axis=-1)\n",
    "    indx_PM =tf.concat([tf.zeros_like(A[:,:,:,:1],dtype=tf.int32),\n",
    "                        tf.ones_like(A[:,:,:,:1],dtype=tf.int32)],axis=-1)\n",
    "    indx_mv =tf.concat([tf.zeros_like(A[:,:,:,:1],dtype=tf.int32),\n",
    "                        tf.ones_like(A[:,:,:,:1],dtype=tf.int32),\n",
    "                        tf.zeros_like(A[:,:,:,:1],dtype=tf.int32),\n",
    "                        tf.ones_like(A[:,:,:,:1],dtype=tf.int32)],axis=-1)\n",
    "    # Estimate A2B\n",
    "    if out_vars == 'WF':\n",
    "        A2B_WF_abs = G_A2B(A, training=False)\n",
    "        A2B_WF_abs = tf.where(A[:,:,:,:2]!=0.0,A2B_WF_abs,0.0)\n",
    "        A2B_PM = tf.zeros_like(A[:,:,:,:2])\n",
    "        A2B_abs = tf.concat([A2B_WF_abs,A2B_PM],axis=-1)\n",
    "    elif out_vars == 'PM':\n",
    "        if te_input:\n",
    "            A2B_PM = G_A2B([A,TE], training=False)\n",
    "            A2B_std = None\n",
    "        elif bayesian:\n",
    "            A2B_PM, A2B_prob = G_A2B(A, training=True)\n",
    "            A2B_mean,A2B_std = tf.dynamic_partition(A2B_prob,indx_mv,num_partitions=2)\n",
    "            A2B_mean = tf.reshape(A2B_mean,A[:,:,:,:2].shape)\n",
    "            A2B_std = tf.reshape(A2B_std,A[:,:,:,:2].shape)\n",
    "        else:\n",
    "            A2B_PM = G_A2B(A, training=False)\n",
    "            A2B_std = None\n",
    "        A2B_PM = tf.where(A[:,:,:,:2]!=0.0,A2B_PM,0.0)\n",
    "        if G_model=='U-Net' or G_model=='MEBCRN':\n",
    "            A2B_R2, A2B_FM = tf.dynamic_partition(A2B_PM,indx_PM,num_partitions=2)\n",
    "            A2B_R2 = tf.reshape(A2B_R2,A[:,:,:,:1].shape)\n",
    "            A2B_FM = tf.reshape(A2B_FM,A[:,:,:,:1].shape)\n",
    "            A2B_FM = (A2B_FM - 0.5) * 2\n",
    "            A2B_FM = tf.where(A[:,:,:,:1]!=0.0,A2B_FM,0.0)\n",
    "            A2B_PM = tf.concat([A2B_R2,A2B_FM],axis=-1)\n",
    "        A2B_WF, A2B2A = wf.acq_to_acq(A,A2B_PM,te=TE,complex_data=(G_model=='complex'))\n",
    "        A2B_WF_real = A2B_WF[:,:,:,0::2]\n",
    "        A2B_WF_imag = A2B_WF[:,:,:,1::2]\n",
    "        A2B_WF_abs = tf.abs(tf.complex(A2B_WF_real,A2B_WF_imag))\n",
    "        A2B_abs = tf.concat([A2B_WF_abs,A2B_PM],axis=-1)\n",
    "    elif out_vars == 'WF-PM':\n",
    "        if te_input:\n",
    "            A2B_abs = G_A2B([A,TE], training=False)\n",
    "        else:\n",
    "            A2B_abs = G_A2B(A, training=False)\n",
    "        A2B_abs = tf.where(A[:,:,:,:4]!=0.0,A2B_abs,0.0)\n",
    "        A2B_WF_abs,A2B_PM = tf.dynamic_partition(A2B_abs,indx_B_abs,num_partitions=2)\n",
    "        A2B_WF_abs = tf.reshape(A2B_WF_abs,A[:,:,:,:2].shape)\n",
    "        A2B_PM = tf.reshape(A2B_PM,A[:,:,:,:2].shape)\n",
    "        if G_model=='U-Net' or G_model=='MEBCRN':\n",
    "            A2B_R2, A2B_FM = tf.dynamic_partition(A2B_PM,indx_PM,num_partitions=2)\n",
    "            A2B_R2 = tf.reshape(A2B_R2,A[:,:,:,:1].shape)\n",
    "            A2B_FM = tf.reshape(A2B_FM,A[:,:,:,:1].shape)\n",
    "            A2B_FM = (A2B_FM - 0.5) * 2\n",
    "            A2B_FM = tf.where(A[:,:,:,:1]!=0.0,A2B_FM,0.0)\n",
    "            A2B_abs = tf.concat([A2B_WF_abs,A2B_R2,A2B_FM],axis=-1)\n",
    "\n",
    "    return [A2B_abs,A2B2A,A2B_std]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0247e12",
   "metadata": {},
   "outputs": [],
   "source": [
    "A, B = next(test_iter)\n",
    "A = tf.expand_dims(A,axis=0)\n",
    "B = tf.expand_dims(B,axis=0)\n",
    "if te_input:\n",
    "    te_orig = wf.gen_TEvar(n_echoes,batch_size,orig=True)\n",
    "    A2B,_,_ = sample_A2B(A, TE=te_orig)\n",
    "else:\n",
    "    A2B, A2B2A, A2B_std = sample_A2B(A)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea3c4da3",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "fig, ((ax1,ax2,ax3,ax4),(ax5,ax6,ax7,ax8))=plt.subplots(figsize=(14, 6),\n",
    "                                                        nrows=2, ncols=4)\n",
    "# Ground truth in the first row\n",
    "w_aux = np.squeeze(A2B[:,:,:,0])\n",
    "W_ok = ax1.imshow(w_aux, cmap='bone',\n",
    "                  interpolation='none', vmin=0, vmax=1)\n",
    "fig.colorbar(W_ok, ax=ax1)\n",
    "ax1.axis('off')\n",
    "\n",
    "f_aux = np.squeeze(A2B[:,:,:,1])\n",
    "F_ok = ax2.imshow(f_aux, cmap='pink',\n",
    "                  interpolation='none', vmin=0, vmax=1)\n",
    "fig.colorbar(F_ok, ax=ax2)\n",
    "ax2.axis('off')\n",
    "\n",
    "r2_aux = np.squeeze(A2B[:,:,:,2])\n",
    "r2_ok = ax3.imshow(r2_aux*r2_sc, cmap='copper',\n",
    "                   interpolation='none', vmin=0, vmax=r2_sc)\n",
    "fig.colorbar(r2_ok, ax=ax3)\n",
    "ax3.axis('off')\n",
    "\n",
    "field_aux = np.squeeze(A2B[:,:,:,3]) \n",
    "field_ok = ax4.imshow(field_aux*fm_sc, cmap='twilight',\n",
    "                      interpolation='none', vmin=-fm_sc/2, vmax=fm_sc/2)\n",
    "fig.colorbar(field_ok, ax=ax4)\n",
    "ax4.axis('off')\n",
    "\n",
    "# Computed maps in the second row\n",
    "wn_aux = np.squeeze(np.abs(tf.complex(B[:,:,:,0],B[:,:,:,1])))\n",
    "W_unet = ax5.imshow(wn_aux, cmap='bone',\n",
    "                    interpolation='none', vmin=0, vmax=1)\n",
    "fig.colorbar(W_unet, ax=ax5)\n",
    "ax5.axis('off')\n",
    "\n",
    "fn_aux = np.squeeze(np.abs(tf.complex(B[:,:,:,2],B[:,:,:,3])))\n",
    "F_unet = ax6.imshow(fn_aux, cmap='pink',\n",
    "                    interpolation='none', vmin=0, vmax=1)\n",
    "fig.colorbar(F_unet, ax=ax6)\n",
    "ax6.axis('off')\n",
    "\n",
    "r2n_aux = np.squeeze(B[:,:,:,4])\n",
    "r2_unet = ax7.imshow(r2n_aux*r2_sc, cmap='copper',\n",
    "                     interpolation='none', vmin=0, vmax=r2_sc)\n",
    "fig.colorbar(r2_unet, ax=ax7)\n",
    "ax7.axis('off')\n",
    "\n",
    "fieldn_aux = np.squeeze(B[:,:,:,5])\n",
    "field_unet = ax8.imshow(fieldn_aux*fm_sc, cmap='twilight',\n",
    "                        interpolation='none', vmin=-fm_sc/2, vmax=fm_sc/2)\n",
    "fig.colorbar(field_unet, ax=ax8)\n",
    "ax8.axis('off')\n",
    "\n",
    "plt.subplots_adjust(top=1,bottom=0,right=1,left=0,hspace=0.1,wspace=0)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "25a5fd39",
   "metadata": {},
   "outputs": [],
   "source": [
    "# DISPLAY ERROR (4 OUTPUTS)\n",
    "fig_err, (ix1,ix2,ix3,ix4) = plt.subplots(figsize=(14, 3), nrows=1, ncols=4)\n",
    "\n",
    "# Ground truth in the first row\n",
    "w_err = np.abs(w_aux-wn_aux)\n",
    "Wn_err = ix1.imshow(w_err, cmap='gray',\n",
    "                    interpolation='none', vmin=0, vmax=0.5)\n",
    "fig_err.colorbar(Wn_err, ax=ix1)\n",
    "# ix1.set_title('Water Error')\n",
    "ix1.axis('off')\n",
    "f_err = np.abs(f_aux-fn_aux)\n",
    "Fn_err = ix2.imshow(f_err, cmap='gray',\n",
    "                    interpolation='none', vmin=0, vmax=0.5)\n",
    "fig_err.colorbar(Fn_err, ax=ix2)\n",
    "# ix2.set_title('Fat Error')\n",
    "ix2.axis('off')\n",
    "r2_err = np.abs(r2_aux-r2n_aux)*r2_sc\n",
    "r2n_err = ix3.imshow(r2_err, cmap='gray',\n",
    "                     interpolation='none', vmin=0, vmax=r2_sc/2)\n",
    "fig_err.colorbar(r2n_err, ax=ix3)\n",
    "# ix3.set_title('R2* Error')\n",
    "ix3.axis('off')\n",
    "field_err = np.abs(field_aux-fieldn_aux)*fm_sc\n",
    "fieldn_err = ix4.imshow(field_err, cmap='gray',\n",
    "                        interpolation='none', vmin=0, vmax=fm_sc/8)\n",
    "fig_err.colorbar(fieldn_err, ax=ix4)\n",
    "# ix4.set_title('Field Error')\n",
    "ix4.axis('off')\n",
    "\n",
    "plt.subplots_adjust(top=1,bottom=0,right=1,left=0,hspace=0.1,wspace=0)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "204425e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "if bayesian:\n",
    "    # DISPLAY STD (4 OUTPUTS)\n",
    "    fig_std, oxs = plt.subplots(figsize=(14, 3), nrows=1, ncols=4)\n",
    "\n",
    "    # STDs in the two subplots\n",
    "    r2_std = np.squeeze(A2B_std[:,:,:,0])\n",
    "    R2n_std = oxs[0].imshow(r2_std, cmap='gray',\n",
    "                        interpolation='none')#, vmin=0, vmax=0.5)\n",
    "    fig_std.colorbar(R2n_std, ax=oxs[0])\n",
    "    oxs[0].axis('off')\n",
    "    fm_std = np.squeeze(A2B_std[:,:,:,1])\n",
    "    FMn_std = oxs[1].imshow(fm_std, cmap='gray',\n",
    "                        interpolation='none')#, vmin=0, vmax=0.5)\n",
    "    fig_std.colorbar(FMn_std, ax=oxs[1])\n",
    "    oxs[1].axis('off')\n",
    "\n",
    "    # STD-weighted A2B2A error\n",
    "    msd = tf.reduce_mean(tf.math.squared_difference(A,A2B2A),axis=-1)\n",
    "    std = tf.reduce_mean(A2B_std,axis=-1)\n",
    "    std = tf.where(std<=0.0,1.0,std)\n",
    "    log_std = tf.math.log(std)\n",
    "    STDw_msd = msd/std\n",
    "    STDw_msd += log_std\n",
    "    LOG_std = oxs[2].imshow(np.squeeze(log_std), cmap='gray',\n",
    "                         interpolation='none')#, vmin=0, vmax=r2_sc/2)\n",
    "    fig_std.colorbar(LOG_std, ax=oxs[2])\n",
    "    oxs[2].axis('off')\n",
    "    DIV_std = oxs[3].imshow(np.squeeze(STDw_msd), cmap='gray',\n",
    "                            interpolation='none', vmin=0, vmax=10)\n",
    "    fig_std.colorbar(DIV_std, ax=oxs[3])\n",
    "    oxs[3].axis('off')\n",
    "\n",
    "    plt.subplots_adjust(top=1,bottom=0,right=1,left=0,hspace=0.1,wspace=0)\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa659c7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "MAE_w = np.mean(tf.abs(w_aux-wn_aux), axis=(0,1))\n",
    "MAE_f = np.mean(tf.abs(f_aux-fn_aux), axis=(0,1))\n",
    "MAE_r2 = np.mean(tf.abs(r2_aux-r2n_aux), axis=(0,1))\n",
    "MAE_fm = np.mean(tf.abs(field_aux-fieldn_aux), axis=(0,1))\n",
    "print('MAEs:',np.round([MAE_w,MAE_f,MAE_r2,MAE_fm],5))\n",
    "print('R2* MAE [1/s]:',np.round(200*MAE_r2,5))\n",
    "print('Field Map MAE [Hz]:',np.round(300*MAE_fm,5))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "11045380",
   "metadata": {},
   "outputs": [],
   "source": [
    "w_ssim = structural_similarity(w_aux,wn_aux,multichannel=False)\n",
    "f_ssim = structural_similarity(f_aux,fn_aux,multichannel=False)\n",
    "r2_ssim = structural_similarity(r2_aux,r2n_aux,multichannel=False)\n",
    "fm_ssim = structural_similarity(field_aux,fieldn_aux,multichannel=False)\n",
    "print('SSIMs:',np.round([w_ssim,f_ssim,r2_ssim,fm_ssim],5))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc1a5f84",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ground-Truth PDFF\n",
    "PDFF_res = f_aux/(w_aux+f_aux)\n",
    "PDFF_res[np.isnan(PDFF_res)] = 0.0\n",
    "\n",
    "# Model Measured PDFF\n",
    "PDFF_gt = fn_aux/(wn_aux+fn_aux)\n",
    "PDFF_gt[np.isnan(PDFF_gt)] = 0.0\n",
    "\n",
    "# Segmentation rectangle (ref. values for test data N°105)\n",
    "verts_list = {1:   (69,109),#ok\n",
    "              2:   (61,89),#ok\n",
    "              3:   (69,68),#ok\n",
    "              4:   (90,60),#ok\n",
    "              5:  (110,68),#ok\n",
    "              6:  (119,89),#ok\n",
    "              7:  (110,109)}#ok\n",
    "\n",
    "left_x,sup_y = verts_list[7]\n",
    "rect_hgt,rect_wdt = 13,13\n",
    "rect_gt = patches.Rectangle((left_x,sup_y),rect_wdt,rect_hgt,\n",
    "                            linewidth=1,edgecolor='y',facecolor='none')\n",
    "rect_res = patches.Rectangle((left_x,sup_y),rect_wdt,rect_hgt,\n",
    "                             linewidth=1,edgecolor='r',facecolor='none')\n",
    "\n",
    "fig_pdff, (ex1,ex2) = plt.subplots(figsize=(10, 4), nrows=1, ncols=2)\n",
    "\n",
    "disp_pdff_ok = ex1.imshow(PDFF_gt, cmap='bone',\n",
    "                          interpolation='none', vmin=0, vmax=1)\n",
    "fig_pdff.colorbar(disp_pdff_ok, ax=ex1)\n",
    "# ex1.set_title('PDFF Ground Truth',{'fontsize':15})\n",
    "# ex1.add_patch(rect_gt)\n",
    "ex1.axis('off')\n",
    "\n",
    "disp_pdff_res = ex2.imshow(PDFF_res, cmap='bone',\n",
    "                           interpolation='none', vmin=0, vmax=1)\n",
    "fig_pdff.colorbar(disp_pdff_res, ax=ex2)\n",
    "# ex2.set_title('Resulting PDFF',{'fontsize':15})\n",
    "# ex2.add_patch(rect_res)\n",
    "ex2.axis('off')\n",
    "\n",
    "plt.subplots_adjust(top = 1, bottom = 0, right = 1, left = 0, \n",
    "                    hspace = 0.1, wspace = 0)\n",
    "plt.margins(0,0)\n",
    "plt.gca().xaxis.set_major_locator(plt.NullLocator())\n",
    "plt.gca().yaxis.set_major_locator(plt.NullLocator())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36783243",
   "metadata": {},
   "outputs": [],
   "source": [
    "r1,r2 = sup_y,(sup_y+rect_hgt)\n",
    "c1,c2 = left_x,(left_x+rect_wdt)\n",
    "PDFF_gt_crop = PDFF_gt[r1:r2,c1:c2]\n",
    "PDFF_res_crop = PDFF_res[r1:r2,c1:c2]\n",
    "\n",
    "print('Median of PDFF in the segmented region:')\n",
    "print('Ground-Truth:\\t',np.median(PDFF_gt_crop))\n",
    "print('Model result:\\t',np.median(PDFF_res_crop))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cf3c3ef2",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "PDFF_res_all = np.array([])\n",
    "PDFF_gt_all = np.array([])\n",
    "rect_hgt,rect_wdt = 13,13\n",
    "for k in verts_list:\n",
    "    left_x,sup_y = verts_list[k]\n",
    "    r1,r2 = sup_y,(sup_y+rect_hgt)\n",
    "    c1,c2 = left_x,(left_x+rect_wdt)\n",
    "    # PDFF crops - magnitude model results\n",
    "    # w_all = all_test_ans[(k_prev+4):(k-4),r1:r2,c1:c2,0]\n",
    "    # f_all = all_test_ans[(k_prev+4):(k-4),r1:r2,c1:c2,1]\n",
    "    # PDFF crops - complex model results\n",
    "    w_all = A2B[:,r1:r2,c1:c2,0]\n",
    "    f_all = A2B[:,r1:r2,c1:c2,1]\n",
    "    PDFF_res_aux = np.median(f_all/(f_all+w_all),axis=(1,2))\n",
    "    PDFF_res_all = np.concatenate((PDFF_res_all,PDFF_res_aux),axis=0)\n",
    "    # PDFF crops - GT magnitude results\n",
    "    # w_all_gt = testY[(k_prev+4):(k-4):,r1:r2,c1:c2,0]\n",
    "    # f_all_gt = testY[(k_prev+4):(k-4),r1:r2,c1:c2,1]\n",
    "    # PDFF crops - GT complex results\n",
    "    w_all_gt = np.abs(tf.complex(B[:,r1:r2,c1:c2,0],\n",
    "                                 B[:,r1:r2,c1:c2,1]))\n",
    "    f_all_gt = np.abs(tf.complex(B[:,r1:r2,c1:c2,2],\n",
    "                                 B[:,r1:r2,c1:c2,3]))\n",
    "    PDFF_gt_aux = np.median(f_all_gt/(f_all_gt+w_all_gt),axis=(1,2))\n",
    "    PDFF_gt_all = np.concatenate((PDFF_gt_all,PDFF_gt_aux),axis=0)\n",
    "\n",
    "# Compute error\n",
    "PDFF_err_list = PDFF_res_all-PDFF_gt_all\n",
    "print('PDFF estimations:',np.round(PDFF_res_all,5))\n",
    "print('Ground-truth:',np.round(PDFF_gt_all,5))\n",
    "print('Errors:',np.round(PDFF_err_list,5))\n",
    "\n",
    "# PDFF crops mean error\n",
    "PDFF_err_mean = np.mean((PDFF_err_list))\n",
    "PDFF_err_std = np.std((PDFF_err_list))\n",
    "print('Mean PDFF error:',np.round(PDFF_err_mean*100,2),\n",
    "      '+-',np.round(PDFF_err_std*100,2),'%')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a4e5bb1",
   "metadata": {},
   "outputs": [],
   "source": [
    "r2_res_all = np.array([])\n",
    "r2_gt_all = np.array([])\n",
    "for k in verts_list:\n",
    "    left_x,sup_y = verts_list[k]\n",
    "    r1,r2 = sup_y,(sup_y+rect_hgt)\n",
    "    c1,c2 = left_x,(left_x+rect_wdt)\n",
    "    # R2* crops - complex model results\n",
    "    r2_all = A2B[:,r1:r2,c1:c2,2]*r2_sc\n",
    "    r2_res_aux = np.mean(r2_all,axis=(1,2))\n",
    "    r2_res_all = np.concatenate((r2_res_all,r2_res_aux),axis=0)\n",
    "    # R2* crops - GT complex results\n",
    "    r2_all_gt = B[:,r1:r2,c1:c2,4]*r2_sc\n",
    "    r2_gt_aux = np.mean(r2_all_gt,axis=(1,2))\n",
    "    r2_gt_all = np.concatenate((r2_gt_all,r2_gt_aux),axis=0)\n",
    "\n",
    "# Compute error\n",
    "r2_err_list = r2_res_all-r2_gt_all\n",
    "print('R2* estimations:',r2_res_all)\n",
    "print('Ground-truth:',r2_gt_all)\n",
    "print('Errors:\\\\n',r2_err_list)\n",
    "\n",
    "# R2* crops mean error\n",
    "r2_err_mean = np.mean((r2_err_list))\n",
    "r2_err_std = np.std((r2_err_list))\n",
    "print('Mean R2* error:',np.round(r2_err_mean,2),\n",
    "      '+-',np.round(r2_err_std,2),'[1/s]')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
